name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  goose-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lint
        uses: ./
        with:
          rule: "Check that all of my yaml files use single quotes"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
