name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  goose-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Lint
        uses: ./
        with:
          rule: "Check that all of my .js function names follow camelCase convention."
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
